In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.16.5)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 9.9 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.9.0 optuna-4.5.0

In [2]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [6]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0 , np.nan)
df.fillna(df.mean() , inplace = True)
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # we dont fit just because of the fear of Data Leakage

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [20]:
from sklearn.ensemble import RandomForestClassifier # A bagging Technique
from sklearn.model_selection import cross_val_score

def objective(trial) :
  n_estimators = trial.suggest_int('n_estimators' , 50 , 200)
  max_depth = trial.suggest_int('max_depth' , 3 , 20)
  model = RandomForestClassifier(n_estimators = n_estimators , max_depth = max_depth , random_state=42) # here random state is a seed
  result = cross_val_score(model , X_train , y_train , cv= 3, scoring = 'accuracy').mean()
  return result

In [23]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=30)

[I 2025-09-14 02:27:38,559] A new study created in memory with name: no-name-d52eb23d-5b9f-4ecc-8854-3142b23c9770
[I 2025-09-14 02:27:39,007] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 76, 'max_depth': 9}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-09-14 02:27:39,714] Trial 1 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:40,220] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:40,715] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 92, 'max_depth': 4}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:41,243] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 7}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:42,123] Trial 5 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 160, 'max_depth': 6}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:43,048] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 158, 'max_depth': 17}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:43,344] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 54, 'max_depth': 5}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:43,702] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 57, 'max_depth': 12}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:44,215] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 80, 'max_depth': 11}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:47,349] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 198, 'max_depth': 15}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:48,097] Trial 11 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 14}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:48,864] Trial 12 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 14}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:49,590] Trial 13 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 20}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:50,455] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 16}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:51,131] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 112, 'max_depth': 13}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:51,941] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 140, 'max_depth': 10}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:53,018] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 18}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:53,654] Trial 18 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 107, 'max_depth': 15}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:54,279] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 104, 'max_depth': 16}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:54,873] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 8}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:55,703] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:56,402] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 115, 'max_depth': 12}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:57,163] Trial 23 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 125, 'max_depth': 15}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:57,838] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 69, 'max_depth': 17}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:27:58,827] Trial 25 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 106, 'max_depth': 13}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:28:00,089] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 157, 'max_depth': 18}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:28:00,930] Trial 27 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:28:01,516] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 97, 'max_depth': 11}. Best is trial 1 with value: 0.7821229050279329.
[I 2025-09-14 02:28:02,206] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 10}. Best is trial 1 with value: 0.7821229050279329.

In [13]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 129, 'max_depth': 16}

In [22]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420856
Best hyperparameters: {'n_estimators': 124, 'max_depth': 7}

In [24]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 117, 'max_depth': 15}

In [14]:
from sklearn.metrics import accuracy_score

best_model = RandomForestClassifier(**study.best_trial.params , random_state = 42)
best_model.fit(X_train , y_train)
y_pred = best_model.predict(X_test)
score = accuracy_score(y_test , y_pred)
print("SCORE IS :::: " , score)

SCORE IS ::::  0.7445887445887446

# **Using Random Sampling in Optuna**
## But Random Sampling is a bit less Optimized Technique when comparing to Bayesian Technique That is used in Tree-Structured Parzen Estimator

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score

In [16]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-09-14 02:22:38,824] A new study created in memory with name: no-name-26d16fb5-06e7-4aa7-b4bf-8c8fefa7935a
[I 2025-09-14 02:22:40,528] Trial 0 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 196, 'max_depth': 18}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:41,005] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 64, 'max_depth': 17}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:41,649] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 64, 'max_depth': 20}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:42,487] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 83, 'max_depth': 12}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:44,082] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 185, 'max_depth': 17}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:44,878] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 17}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:46,228] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 134, 'max_depth': 5}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:47,209] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 146, 'max_depth': 9}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:48,332] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 176, 'max_depth': 6}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:49,448] Trial 9 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 191, 'max_depth': 3}. Best is trial 0 with value: 0.7746741154562384.
[I 2025-09-14 02:22:50,602] Trial 10 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 19}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:51,107] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 57, 'max_depth': 10}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:51,515] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:52,254] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 8}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:52,924] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 102, 'max_depth': 8}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:54,157] Trial 15 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 157, 'max_depth': 9}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:54,937] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 82, 'max_depth': 5}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:55,577] Trial 17 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 63, 'max_depth': 4}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:56,402] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 85, 'max_depth': 9}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:57,156] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 111, 'max_depth': 14}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:57,820] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 11}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:58,703] Trial 21 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 152, 'max_depth': 6}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-09-14 02:22:59,021] Trial 22 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 50, 'max_depth': 7}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:22:59,890] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:00,295] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:01,554] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 13}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:02,508] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 134, 'max_depth': 6}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:03,459] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 20}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:04,244] Trial 28 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 89, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:05,535] Trial 29 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 184, 'max_depth': 9}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:06,149] Trial 30 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 93, 'max_depth': 12}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:07,609] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 135, 'max_depth': 11}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:09,293] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 8}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:11,238] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 11}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:12,716] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:14,484] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 136, 'max_depth': 13}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:15,800] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 144, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:16,193] Trial 37 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 66, 'max_depth': 6}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:17,398] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 20}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:18,409] Trial 39 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 16}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:19,014] Trial 40 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 88, 'max_depth': 11}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:21,176] Trial 41 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 195, 'max_depth': 4}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:22,359] Trial 42 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 134, 'max_depth': 13}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:22,779] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 60, 'max_depth': 6}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:23,686] Trial 44 finished with value: 0.756052141527002 and parameters: {'n_estimators': 160, 'max_depth': 3}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:24,399] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:26,152] Trial 46 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 177, 'max_depth': 14}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:27,525] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 14}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:27,903] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 56, 'max_depth': 13}. Best is trial 22 with value: 0.7802607076350093.
[I 2025-09-14 02:23:29,190] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 199, 'max_depth': 11}. Best is trial 22 with value: 0.7802607076350093.

In [17]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 50, 'max_depth': 7}

# **Optuna Visualization Techniques For Step By Step Investigation System**

In [18]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [19]:
plot_optimization_history(study).show()

In [26]:
plot_parallel_coordinate(study).show()

In [27]:
plot_slice(study).show()

In [28]:
plot_contour(study).show()

In [29]:
plot_param_importances(study).show()

# **Using ML Algorithms as HyperParameters (Seems Ridiculous)**

In [30]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [31]:
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [32]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-09-14 02:36:24,228] A new study created in memory with name: no-name-f0e9482f-4a0a-49d9-8f46-cf18c25c294e
[I 2025-09-14 02:36:26,591] Trial 0 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 106, 'learning_rate': 0.18374070456626299, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7560521415270017.
[I 2025-09-14 02:36:26,631] Trial 1 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.3178046663751258, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7560521415270017.
[I 2025-09-14 02:36:27,826] Trial 2 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 209, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-09-14 02:36:28,746] Trial 3 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 207, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-09-14 02:36:28,780] Trial 4 finished with value: 0.7262569832402236 and parameters: {'classifier': 'SVM', 'C': 2.2572424110395, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-09-14 02:36:30,194] Trial 5 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-09-14 02:36:31,163] Trial 6 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 214, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-09-14 02:36:32,383] Trial 7 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 215, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-09-14 02:36:37,931] Trial 8 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 169, 'learning_rate': 0.050031283727135535, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-09-14 02:36:38,011] Trial 9 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2827541929409295, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:38,489] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 80.40356250246347, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:38,797] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 79.35654098065783, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:39,074] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 73.15888104552022, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:39,113] Trial 13 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24441410714758954, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:39,152] Trial 14 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.1437279632190545, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:39,193] Trial 15 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8296636673382282, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7858472998137803.
[I 2025-09-14 02:36:39,232] Trial 16 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1358316913247658, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:39,567] Trial 17 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 50, 'learning_rate': 0.014516493721146431, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:39,610] Trial 18 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 10.149731226917242, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:39,645] Trial 19 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.11154943674952258, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,232] Trial 20 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 296, 'learning_rate': 0.29523250535514867, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,265] Trial 21 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4684607002502778, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,302] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24805763701391773, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,348] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.092725232885559, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,394] Trial 24 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.1137010661532317, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,429] Trial 25 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5729253062376765, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,491] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.029045573650566, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:42,529] Trial 27 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23961075347450847, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:43,361] Trial 28 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 136, 'learning_rate': 0.010411414063227955, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:43,399] Trial 29 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 1.7093054849569478, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,391] Trial 30 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 299, 'learning_rate': 0.05446593879974562, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,445] Trial 31 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7517996488141995, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,500] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2565102371998765, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,553] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.41878736190300864, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,613] Trial 34 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9496237883865464, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:48,680] Trial 35 finished with value: 0.7597765363128492 and parameters: {'classifier': 'SVM', 'C': 0.17594235267563457, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:49,989] Trial 36 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 66, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:50,067] Trial 37 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.4016289809085338, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:52,715] Trial 38 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 254, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:52,771] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.952969356539514, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,442] Trial 40 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,495] Trial 41 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22828138063833636, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,555] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17120525471110695, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,608] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10321016546751498, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,661] Trial 44 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10092806649432746, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,718] Trial 45 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 0.1001810335667298, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,791] Trial 46 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14835747317998824, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,871] Trial 47 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.1549594729759929, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:53,951] Trial 48 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1621208994942649, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:36:54,974] Trial 49 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 164, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,371] Trial 50 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 258, 'learning_rate': 0.11137279569397024, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,422] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15652051389646882, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,477] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10304953632392905, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,534] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16728590976087823, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,584] Trial 54 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3368868029529083, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,747] Trial 55 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.087404482856407, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,802] Trial 56 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17128403936592854, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,851] Trial 57 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14098205785456813, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,892] Trial 58 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.3140289244547165, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:02,923] Trial 59 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1979110128303629, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,428] Trial 60 finished with value: 0.756052141527002 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 135, 'learning_rate': 0.02102274012958372, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,460] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1364803470958321, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,491] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13358736481938366, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,523] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1506108680683193, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,554] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14290117065374927, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,604] Trial 65 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.3057134537104989, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,636] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13687260950652363, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,676] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21158728460264734, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,753] Trial 68 finished with value: 0.74487895716946 and parameters: {'classifier': 'SVM', 'C': 0.6206778631345757, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:04,810] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1233895346162893, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,035] Trial 70 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 95, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,100] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14180728389246025, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,173] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13600510017127126, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,226] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23100724275061188, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,353] Trial 74 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.20102142222387634, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:06,529] Trial 75 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.533967859744514, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,530] Trial 76 finished with value: 0.7243947858472998 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 142, 'learning_rate': 0.026998038722629947, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,578] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30876397732602207, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,636] Trial 78 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4140508572412853, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,704] Trial 79 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.9207683863185636, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,760] Trial 80 finished with value: 0.7094972067039107 and parameters: {'classifier': 'SVM', 'C': 0.13557114241175308, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.
[I 2025-09-14 02:37:15,812] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1326514900137966, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7895716945996275.

In [33]:
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1358316913247658, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [34]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.756052,2025-09-14 02:36:24.231022,2025-09-14 02:36:26.590999,0 days 00:00:02.359977,NaN,NaN,GradientBoosting,NaN,NaN,0.183741,8.0,7.0,4.0,106.0,COMPLETE
1,1,0.726257,2025-09-14 02:36:26.591925,2025-09-14 02:36:26.631146,0 days 00:00:00.039221,0.317805,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.769088,2025-09-14 02:36:26.632692,2025-09-14 02:36:27.826564,0 days 00:00:01.193872,NaN,True,RandomForest,NaN,NaN,NaN,16.0,5.0,7.0,209.0,COMPLETE
3,3,0.769088,2025-09-14 02:36:27.827546,2025-09-14 02:36:28.746164,0 days 00:00:00.918618,NaN,False,RandomForest,NaN,NaN,NaN,7.0,10.0,5.0,207.0,COMPLETE
4,4,0.726257,2025-09-14 02:36:28.747202,2025-09-14 02:36:28.780401,0 days 00:00:00.033199,2.257242,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.754190,2025-09-14 02:37:17.644540,2025-09-14 02:37:19.167746,0 days 00:00:01.523206,NaN,NaN,GradientBoosting,NaN,NaN,0.098493,5.0,7.0,3.0,184.0,COMPLETE
96,96,0.763501,2025-09-14 02:37:19.168750,2025-09-14 02:37:19.208059,0 days 00:00:00.039309,0.202834,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2025-09-14 02:37:19.208996,2025-09-14 02:37:19.239042,0 days 00:00:00.030046,0.149594,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2025-09-14 02:37:19.240009,2025-09-14 02:37:19.276324,0 days 00:00:00.036315,0.123476,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.787709,2025-09-14 02:37:19.277400,2025-09-14 02:37:19.308821,0 days 00:00:00.031421,0.178652,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [36]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.5.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.0.4)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.16.5)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.27.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.1)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.2)
Downloading optuna_integration-4.5.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 3.3 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.5.0

In [37]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2025-09-14 02:40:04,127] A new study created in memory with name: no-name-ac09b7f3-fcbf-4645-959f-dbdf424e3c70

[0]	train-mlogloss:0.91530	eval-mlogloss:0.90431
[1]	train-mlogloss:0.75021	eval-mlogloss:0.71858
[2]	train-mlogloss:0.59189	eval-mlogloss:0.55062
[3]	train-mlogloss:0.47614	eval-mlogloss:0.42563
[4]	train-mlogloss:0.40248	eval-mlogloss:0.34981
[5]	train-mlogloss:0.34036	eval-mlogloss:0.28371
[6]	train-mlogloss:0.30145	eval-mlogloss:0.24567
[7]	train-mlogloss:0.29124	eval-mlogloss:0.23478
[8]	train-mlogloss:0.28994	eval-mlogloss:0.23429
[9]	train-mlogloss:0.26164	eval-mlogloss:0.20161
[10]	train-mlogloss:0.25533	eval-mlogloss:0.19154
[11]	train-mlogloss:0.25529	eval-mlogloss:0.19224
[12]	train-mlogloss:0.25470	eval-mlogloss:0.19192
[13]	train-mlogloss:0.25576	eval-mlogloss:0.19600
[14]	train-mlogloss:0.25498	eval-mlogloss:0.19458
[15]	train-mlogloss:0.25397	eval-mlogloss:0.19335
[16]	train-mlogloss:0.25297	eval-mlogloss:0.18940
[17]	train-mlogloss:0.25220	eval-mlogloss:0.18906
[18]	train-mlogloss:0.24422	eval-mlogloss:0.17882
[19]	train-mlogloss:0.24429	eval-mlogloss:0.17849
[20]	train-mlogloss:0.24434	eval-mlogloss:0.17852
[21]	train-mlogloss:0.24397	eval-mlogloss:0.17868
[22]	train-mlogloss:0.24317	eval-mlogloss:0.17470
[23]	train-mlogloss:0.24329	eval-mlogloss:0.17446
[24]	train-mlogloss:0.24372	eval-mlogloss:0.17443
[25]	train-mlogloss:0.24164	eval-mlogloss:0.17414
[26]	train-mlogloss:0.24154	eval-mlogloss:0.17309
[27]	train-mlogloss:0.24184	eval-mlogloss:0.17300
[28]	train-mlogloss:0.24152	eval-mlogloss:0.17333
[29]	train-mlogloss:0.24144	eval-mlogloss:0.17316
[30]	train-mlogloss:0.24200	eval-mlogloss:0.17512
[31]	train-mlogloss:0.24090	eval-mlogloss:0.17354
[32]	train-mlogloss:0.24040	eval-mlogloss:0.17327
[33]	train-mlogloss:0.24020	eval-mlogloss:0.17212
[34]	train-mlogloss:0.23996	eval-mlogloss:0.17166
[35]	train-mlogloss:0.23991	eval-mlogloss:0.17171
[36]	train-mlogloss:0.24013	eval-mlogloss:0.17209
[37]	train-mlogloss:0.23952	eval-mlogloss:0.17337
[38]	train-mlogloss:0.23922	eval-mlogloss:0.17388
[39]	train-mlogloss:0.23926	eval-mlogloss:0.17389
[40]	train-mlogloss:0.23795	eval-mlogloss:0.17355
[41]	train-mlogloss:0.23716	eval-mlogloss:0.17260
[42]	train-mlogloss:0.23669	eval-mlogloss:0.17059
[43]	train-mlogloss:0.23746	eval-mlogloss:0.17207
[44]	train-mlogloss:0.23698	eval-mlogloss:0.17151
[45]	train-mlogloss:0.23586	eval-mlogloss:0.17015
[46]	train-mlogloss:0.23526	eval-mlogloss:0.16770
[47]	train-mlogloss:0.23537	eval-mlogloss:0.16899
[48]	train-mlogloss:0.23560	eval-mlogloss:0.16813
[49]	train-mlogloss:0.23451	eval-mlogloss:0.16644
[50]	train-mlogloss:0.22527	eval-mlogloss:0.15424
[51]	train-mlogloss:0.22544	eval-mlogloss:0.15413
[52]	train-mlogloss:0.22552	eval-mlogloss:0.15471
[53]	train-mlogloss:0.22553	eval-mlogloss:0.15433
[54]	train-mlogloss:0.22519	eval-mlogloss:0.15296
[55]	train-mlogloss:0.22467	eval-mlogloss:0.15246
[56]	train-mlogloss:0.22459	eval-mlogloss:0.15182
[57]	train-mlogloss:0.22471	eval-mlogloss:0.15200
[58]	train-mlogloss:0.22479	eval-mlogloss:0.15214
[59]	train-mlogloss:0.22461	eval-mlogloss:0.15197
[60]	train-mlogloss:0.22423	eval-mlogloss:0.15200
[61]	train-mlogloss:0.22345	eval-mlogloss:0.15166
[62]	train-mlogloss:0.22304	eval-mlogloss:0.15142
[63]	train-mlogloss:0.22290	eval-mlogloss:0.15060
[64]	train-mlogloss:0.22285	eval-mlogloss:0.15042
[65]	train-mlogloss:0.22341	eval-mlogloss:0.15171
[66]	train-mlogloss:0.22302	eval-mlogloss:0.15053
[67]	train-mlogloss:0.22220	eval-mlogloss:0.15026
[68]	train-mlogloss:0.22224	eval-mlogloss:0.15012
[69]	train-mlogloss:0.22172	eval-mlogloss:0.14947
[70]	train-mlogloss:0.22176	eval-mlogloss:0.14914
[71]	train-mlogloss:0.22176	eval-mlogloss:0.14943
[72]	train-mlogloss:0.22187	eval-mlogloss:0.14887
[73]	train-mlogloss:0.22162	eval-mlogloss:0.14880
[74]	train-mlogloss:0.22163	eval-mlogloss:0.14882
[75]	train-mlogloss:0.22174	eval-mlogloss:0.14944
[76]	train-mlogloss:0.22165	eval-mlogloss:0.14907
[77]	train-mlogloss:0.22155	eval-mlogloss:0.15048
[78]	train-mlogloss:0.22161	eval-mlogloss:0.15093
[79]	train-mlogloss:0.22172	eval-mlogloss:0.15165
[80]	train-mlogloss:0.22158	eval-mlogloss:0.15148
[81]	train-mlogloss:0.22152	eval-mlogloss:0.15172
[82]	train-mlogloss:0.22148	eval-mlogloss:0.15179
[83]	train-mlogloss:0.22136	eval-mlogloss:0.15091
[84]	train-mlogloss:0.22143	eval-mlogloss:0.15119
[85]	train-mlogloss:0.22133	eval-mlogloss:0.15076
[86]	train-mlogloss:0.22131	eval-mlogloss:0.15095
[87]	train-mlogloss:0.22062	eval-mlogloss:0.15048
[88]	train-mlogloss:0.22013	eval-mlogloss:0.14994
[89]	train-mlogloss:0.22015	eval-mlogloss:0.14979
[90]	train-mlogloss:0.22029	eval-mlogloss:0.14980
[91]	train-mlogloss:0.22050	eval-mlogloss:0.15044
[92]	train-mlogloss:0.22018	eval-mlogloss:0.14981
[93]	train-mlogloss:0.22011	eval-mlogloss:0.14725
[94]	train-mlogloss:0.22015	eval-mlogloss:0.14774
[95]	train-mlogloss:0.22058	eval-mlogloss:0.14902
[96]	train-mlogloss:0.22042	eval-mlogloss:0.14931
[97]	train-mlogloss:0.22010	eval-mlogloss:0.14819
[98]	train-mlogloss:0.22085	eval-mlogloss:0.14999
[99]	train-mlogloss:0.21940	eval-mlogloss:0.14810
[100]	train-mlogloss:0.21887	eval-mlogloss:0.14689
[101]	train-mlogloss:0.21871	eval-mlogloss:0.14698
[102]	train-mlogloss:0.21889	eval-mlogloss:0.14759
[103]	train-mlogloss:0.21906	eval-mlogloss:0.14775
[104]	train-mlogloss:0.21908	eval-mlogloss:0.14819
[105]	train-mlogloss:0.21856	eval-mlogloss:0.14690
[106]	train-mlogloss:0.21885	eval-mlogloss:0.14804
[107]	train-mlogloss:0.21948	eval-mlogloss:0.14989
[108]	train-mlogloss:0.21889	eval-mlogloss:0.14860
[109]	train-mlogloss:0.21855	eval-mlogloss:0.14757
[110]	train-mlogloss:0.21877	eval-mlogloss:0.14813
[111]	train-mlogloss:0.21860	eval-mlogloss:0.14725
[112]	train-mlogloss:0.21833	eval-mlogloss:0.14623
[113]	train-mlogloss:0.21835	eval-mlogloss:0.14611
[114]	train-mlogloss:0.21842	eval-mlogloss:0.14638
[115]	train-mlogloss:0.21863	eval-mlogloss:0.14972
[116]	train-mlogloss:0.21873	eval-mlogloss:0.15020
[117]	train-mlogloss:0.21849	eval-mlogloss:0.14806
[118]	train-mlogloss:0.21850	eval-mlogloss:0.14752
[119]	train-mlogloss:0.21854	eval-mlogloss:0.14791
[120]	train-mlogloss:0.21788	eval-mlogloss:0.14695
[121]	train-mlogloss:0.21725	eval-mlogloss:0.14686
[122]	train-mlogloss:0.21722	eval-mlogloss:0.14750
[123]	train-mlogloss:0.21736	eval-mlogloss:0.14773
[124]	train-mlogloss:0.21743	eval-mlogloss:0.14775
[125]	train-mlogloss:0.21703	eval-mlogloss:0.14689
[126]	train-mlogloss:0.21703	eval-mlogloss:0.14699
[127]	train-mlogloss:0.21692	eval-mlogloss:0.14626
[128]	train-mlogloss:0.21692	eval-mlogloss:0.14684
[129]	train-mlogloss:0.21640	eval-mlogloss:0.14652
[130]	train-mlogloss:0.21666	eval-mlogloss:0.14715
[131]	train-mlogloss:0.21719	eval-mlogloss:0.14879
[132]	train-mlogloss:0.21609	eval-mlogloss:0.14639
[133]	train-mlogloss:0.21598	eval-mlogloss:0.14592
[134]	train-mlogloss:0.21599	eval-mlogloss:0.14607
[135]	train-mlogloss:0.21618	eval-mlogloss:0.14639
[136]	train-mlogloss:0.21628	eval-mlogloss:0.14652
[137]	train-mlogloss:0.21608	eval-mlogloss:0.14575
[138]	train-mlogloss:0.21591	eval-mlogloss:0.14507
[139]	train-mlogloss:0.21611	eval-mlogloss:0.14462
[140]	train-mlogloss:0.21617	eval-mlogloss:0.14455
[141]	train-mlogloss:0.21622	eval-mlogloss:0.14457
[142]	train-mlogloss:0.21653	eval-mlogloss:0.14570
[143]	train-mlogloss:0.21645	eval-mlogloss:0.14603
[144]	train-mlogloss:0.21589	eval-mlogloss:0.14513
[145]	train-mlogloss:0.21613	eval-mlogloss:0.14651
[146]	train-mlogloss:0.21583	eval-mlogloss:0.14461
[147]	train-mlogloss:0.21583	eval-mlogloss:0.14561
[148]	train-mlogloss:0.21602	eval-mlogloss:0.14678
[149]	train-mlogloss:0.21608	eval-mlogloss:0.14678
[150]	train-mlogloss:0.21524	eval-mlogloss:0.14463
[151]	train-mlogloss:0.21519	eval-mlogloss:0.14481
[152]	train-mlogloss:0.21525	eval-mlogloss:0.14480
[153]	train-mlogloss:0.21520	eval-mlogloss:0.14453
[154]	train-mlogloss:0.21547	eval-mlogloss:0.14365
[155]	train-mlogloss:0.21569	eval-mlogloss:0.14350
[156]	train-mlogloss:0.21580	eval-mlogloss:0.14374
[157]	train-mlogloss:0.21577	eval-mlogloss:0.14366
[158]	train-mlogloss:0.21564	eval-mlogloss:0.14391
[159]	train-mlogloss:0.21541	eval-mlogloss:0.14434
[160]	train-mlogloss:0.21544	eval-mlogloss:0.14422
[161]	train-mlogloss:0.21539	eval-mlogloss:0.14435
[162]	train-mlogloss:0.21555	eval-mlogloss:0.14438
[163]	train-mlogloss:0.21575	eval-mlogloss:0.14419
[164]	train-mlogloss:0.21541	eval-mlogloss:0.14471
[165]	train-mlogloss:0.21529	eval-mlogloss:0.14423
[166]	train-mlogloss:0.21539	eval-mlogloss:0.14457
[167]	train-mlogloss:0.21539	eval-mlogloss:0.14432
[168]	train-mlogloss:0.21536	eval-mlogloss:0.14499
[169]	train-mlogloss:0.21541	eval-mlogloss:0.14512
[170]	train-mlogloss:0.21548	eval-mlogloss:0.14563
[171]	train-mlogloss:0.21534	eval-mlogloss:0.14611
[172]	train-mlogloss:0.21493	eval-mlogloss:0.14507
[173]	train-mlogloss:0.21487	eval-mlogloss:0.14472
[174]	train-mlogloss:0.21488	eval-mlogloss:0.14552
[175]	train-mlogloss:0.21486	eval-mlogloss:0.14469
[176]	train-mlogloss:0.21494	eval-mlogloss:0.14437
[177]	train-mlogloss:0.21485	eval-mlogloss:0.14458
[178]	train-mlogloss:0.21477	eval-mlogloss:0.14474
[179]	train-mlogloss:0.21489	eval-mlogloss:0.14457
[180]	train-mlogloss:0.21539	eval-mlogloss:0.14448
[181]	train-mlogloss:0.21501	eval-mlogloss:0.14444
[182]	train-mlogloss:0.21501	eval-mlogloss:0.14383
[183]	train-mlogloss:0.21492	eval-mlogloss:0.14438
[184]	train-mlogloss:0.21526	eval-mlogloss:0.14445

[I 2025-09-14 02:40:05,095] Trial 0 finished with value: 1.0 and parameters: {'lambda': 1.2250904678513507e-07, 'alpha': 3.6114636955552215e-07, 'eta': 0.23828434454277586, 'gamma': 0.023318103669313976, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.4588392809168451, 'colsample_bytree': 0.5177577376554756}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.93739	eval-mlogloss:0.93529
[1]	train-mlogloss:0.75798	eval-mlogloss:0.74707
[2]	train-mlogloss:0.62329	eval-mlogloss:0.60578
[3]	train-mlogloss:0.52013	eval-mlogloss:0.50116
[4]	train-mlogloss:0.44022	eval-mlogloss:0.41806
[5]	train-mlogloss:0.37466	eval-mlogloss:0.34748
[6]	train-mlogloss:0.32293	eval-mlogloss:0.29446
[7]	train-mlogloss:0.28324	eval-mlogloss:0.25077
[8]	train-mlogloss:0.25168	eval-mlogloss:0.21511
[9]	train-mlogloss:0.22790	eval-mlogloss:0.18721
[10]	train-mlogloss:0.20877	eval-mlogloss:0.16456
[11]	train-mlogloss:0.19643	eval-mlogloss:0.14894
[12]	train-mlogloss:0.18711	eval-mlogloss:0.13964
[13]	train-mlogloss:0.18142	eval-mlogloss:0.13153
[14]	train-mlogloss:0.17736	eval-mlogloss:0.12583
[15]	train-mlogloss:0.17421	eval-mlogloss:0.12081
[16]	train-mlogloss:0.17139	eval-mlogloss:0.11646
[17]	train-mlogloss:0.16745	eval-mlogloss:0.11219
[18]	train-mlogloss:0.16445	eval-mlogloss:0.10727
[19]	train-mlogloss:0.16432	eval-mlogloss:0.10710
[20]	train-mlogloss:0.16422	eval-mlogloss:0.10672
[21]	train-mlogloss:0.16414	eval-mlogloss:0.10674
[22]	train-mlogloss:0.16357	eval-mlogloss:0.10581
[23]	train-mlogloss:0.16346	eval-mlogloss:0.10542
[24]	train-mlogloss:0.16274	eval-mlogloss:0.10498
[25]	train-mlogloss:0.16215	eval-mlogloss:0.10464
[26]	train-mlogloss:0.16202	eval-mlogloss:0.10360
[27]	train-mlogloss:0.16161	eval-mlogloss:0.10336
[28]	train-mlogloss:0.16149	eval-mlogloss:0.10322
[29]	train-mlogloss:0.15996	eval-mlogloss:0.10077
[30]	train-mlogloss:0.15993	eval-mlogloss:0.10073
[31]	train-mlogloss:0.15939	eval-mlogloss:0.10048
[32]	train-mlogloss:0.15903	eval-mlogloss:0.10027
[33]	train-mlogloss:0.15892	eval-mlogloss:0.09870
[34]	train-mlogloss:0.15871	eval-mlogloss:0.09845
[35]	train-mlogloss:0.15842	eval-mlogloss:0.09833
[36]	train-mlogloss:0.15820	eval-mlogloss:0.09821
[37]	train-mlogloss:0.15807	eval-mlogloss:0.09816
[38]	train-mlogloss:0.15801	eval-mlogloss:0.09784
[39]	train-mlogloss:0.15780	eval-mlogloss:0.09756
[40]	train-mlogloss:0.15751	eval-mlogloss:0.09742
[41]	train-mlogloss:0.15726	eval-mlogloss:0.09719
[42]	train-mlogloss:0.15707	eval-mlogloss:0.09715
[43]	train-mlogloss:0.15687	eval-mlogloss:0.09708
[44]	train-mlogloss:0.15658	eval-mlogloss:0.09665
[45]	train-mlogloss:0.15620	eval-mlogloss:0.09630
[46]	train-mlogloss:0.15617	eval-mlogloss:0.09604
[47]	train-mlogloss:0.15617	eval-mlogloss:0.09614
[48]	train-mlogloss:0.15614	eval-mlogloss:0.09624
[49]	train-mlogloss:0.15610	eval-mlogloss:0.09617
[50]	train-mlogloss:0.15607	eval-mlogloss:0.09625
[51]	train-mlogloss:0.15604	eval-mlogloss:0.09635
[52]	train-mlogloss:0.15588	eval-mlogloss:0.09619
[53]	train-mlogloss:0.15586	eval-mlogloss:0.09635
[54]	train-mlogloss:0.15586	eval-mlogloss:0.09623
[55]	train-mlogloss:0.15551	eval-mlogloss:0.09601
[56]	train-mlogloss:0.15540	eval-mlogloss:0.09587
[57]	train-mlogloss:0.15542	eval-mlogloss:0.09565
[58]	train-mlogloss:0.15544	eval-mlogloss:0.09547
[59]	train-mlogloss:0.15497	eval-mlogloss:0.09513
[60]	train-mlogloss:0.15471	eval-mlogloss:0.09511
[61]	train-mlogloss:0.15440	eval-mlogloss:0.09497
[62]	train-mlogloss:0.15426	eval-mlogloss:0.09472
[63]	train-mlogloss:0.15416	eval-mlogloss:0.09342
[64]	train-mlogloss:0.15399	eval-mlogloss:0.09327
[65]	train-mlogloss:0.15398	eval-mlogloss:0.09311
[66]	train-mlogloss:0.15384	eval-mlogloss:0.09305
[67]	train-mlogloss:0.15390	eval-mlogloss:0.09310
[68]	train-mlogloss:0.15373	eval-mlogloss:0.09303
[69]	train-mlogloss:0.15359	eval-mlogloss:0.09294
[70]	train-mlogloss:0.15353	eval-mlogloss:0.09291
[71]	train-mlogloss:0.15344	eval-mlogloss:0.09308
[72]	train-mlogloss:0.15340	eval-mlogloss:0.09279
[73]	train-mlogloss:0.15336	eval-mlogloss:0.09274
[74]	train-mlogloss:0.15336	eval-mlogloss:0.09249
[75]	train-mlogloss:0.15336	eval-mlogloss:0.09258
[76]	train-mlogloss:0.15338	eval-mlogloss:0.09227
[77]	train-mlogloss:0.15325	eval-mlogloss:0.09213
[78]	train-mlogloss:0.15309	eval-mlogloss:0.09205
[79]	train-mlogloss:0.15310	eval-mlogloss:0.09218
[80]	train-mlogloss:0.15308	eval-mlogloss:0.09229
[81]	train-mlogloss:0.15304	eval-mlogloss:0.09119
[82]	train-mlogloss:0.15301	eval-mlogloss:0.09102
[83]	train-mlogloss:0.15299	eval-mlogloss:0.09113
[84]	train-mlogloss:0.15287	eval-mlogloss:0.09086
[85]	train-mlogloss:0.15286	eval-mlogloss:0.09068
[86]	train-mlogloss:0.15287	eval-mlogloss:0.09080
[87]	train-mlogloss:0.15277	eval-mlogloss:0.09076
[88]	train-mlogloss:0.15258	eval-mlogloss:0.09060
[89]	train-mlogloss:0.15163	eval-mlogloss:0.08926
[90]	train-mlogloss:0.15155	eval-mlogloss:0.08926
[91]	train-mlogloss:0.15155	eval-mlogloss:0.08887
[92]	train-mlogloss:0.15143	eval-mlogloss:0.08885
[93]	train-mlogloss:0.15150	eval-mlogloss:0.08871
[94]	train-mlogloss:0.15150	eval-mlogloss:0.08903
[95]	train-mlogloss:0.15143	eval-mlogloss:0.08901
[96]	train-mlogloss:0.15146	eval-mlogloss:0.08881
[97]	train-mlogloss:0.15144	eval-mlogloss:0.08888
[98]	train-mlogloss:0.15150	eval-mlogloss:0.08887
[99]	train-mlogloss:0.15148	eval-mlogloss:0.08824
[100]	train-mlogloss:0.15150	eval-mlogloss:0.08821
[101]	train-mlogloss:0.15141	eval-mlogloss:0.08824
[102]	train-mlogloss:0.15135	eval-mlogloss:0.08838
[103]	train-mlogloss:0.15118	eval-mlogloss:0.08822
[104]	train-mlogloss:0.15113	eval-mlogloss:0.08837
[105]	train-mlogloss:0.15114	eval-mlogloss:0.08817
[106]	train-mlogloss:0.15113	eval-mlogloss:0.08839
[107]	train-mlogloss:0.15114	eval-mlogloss:0.08873
[108]	train-mlogloss:0.15111	eval-mlogloss:0.08873
[109]	train-mlogloss:0.15099	eval-mlogloss:0.08870
[110]	train-mlogloss:0.15094	eval-mlogloss:0.08877
[111]	train-mlogloss:0.15085	eval-mlogloss:0.08872
[112]	train-mlogloss:0.15081	eval-mlogloss:0.08872
[113]	train-mlogloss:0.15085	eval-mlogloss:0.08807
[114]	train-mlogloss:0.15079	eval-mlogloss:0.08795
[115]	train-mlogloss:0.15080	eval-mlogloss:0.08805
[116]	train-mlogloss:0.15070	eval-mlogloss:0.08795
[117]	train-mlogloss:0.15055	eval-mlogloss:0.08766
[118]	train-mlogloss:0.15037	eval-mlogloss:0.08745
[119]	train-mlogloss:0.15034	eval-mlogloss:0.08742
[120]	train-mlogloss:0.15020	eval-mlogloss:0.08714
[121]	train-mlogloss:0.15016	eval-mlogloss:0.08700
[122]	train-mlogloss:0.14997	eval-mlogloss:0.08700
[123]	train-mlogloss:0.14993	eval-mlogloss:0.08718
[124]	train-mlogloss:0.14994	eval-mlogloss:0.08671
[125]	train-mlogloss:0.14995	eval-mlogloss:0.08678
[126]	train-mlogloss:0.14991	eval-mlogloss:0.08687
[127]	train-mlogloss:0.14982	eval-mlogloss:0.08676
[128]	train-mlogloss:0.14980	eval-mlogloss:0.08703
[129]	train-mlogloss:0.14976	eval-mlogloss:0.08700
[130]	train-mlogloss:0.14978	eval-mlogloss:0.08689
[131]	train-mlogloss:0.14973	eval-mlogloss:0.08694
[132]	train-mlogloss:0.14973	eval-mlogloss:0.08617
[133]	train-mlogloss:0.14972	eval-mlogloss:0.08627
[134]	train-mlogloss:0.14974	eval-mlogloss:0.08640
[135]	train-mlogloss:0.14972	eval-mlogloss:0.08668
[136]	train-mlogloss:0.14972	eval-mlogloss:0.08671
[137]	train-mlogloss:0.14962	eval-mlogloss:0.08662
[138]	train-mlogloss:0.14960	eval-mlogloss:0.08690
[139]	train-mlogloss:0.14947	eval-mlogloss:0.08680
[140]	train-mlogloss:0.14947	eval-mlogloss:0.08687
[141]	train-mlogloss:0.14947	eval-mlogloss:0.08696
[142]	train-mlogloss:0.14950	eval-mlogloss:0.08705
[143]	train-mlogloss:0.14939	eval-mlogloss:0.08682
[144]	train-mlogloss:0.14932	eval-mlogloss:0.08683
[145]	train-mlogloss:0.14936	eval-mlogloss:0.08703
[146]	train-mlogloss:0.14930	eval-mlogloss:0.08741
[147]	train-mlogloss:0.14925	eval-mlogloss:0.08695
[148]	train-mlogloss:0.14924	eval-mlogloss:0.08693
[149]	train-mlogloss:0.14913	eval-mlogloss:0.08692
[150]	train-mlogloss:0.14912	eval-mlogloss:0.08673
[151]	train-mlogloss:0.14913	eval-mlogloss:0.08655
[152]	train-mlogloss:0.14902	eval-mlogloss:0.08662
[153]	train-mlogloss:0.14899	eval-mlogloss:0.08660
[154]	train-mlogloss:0.14896	eval-mlogloss:0.08649
[155]	train-mlogloss:0.14889	eval-mlogloss:0.08657
[156]	train-mlogloss:0.14881	eval-mlogloss:0.08654
[157]	train-mlogloss:0.14877	eval-mlogloss:0.08648
[158]	train-mlogloss:0.14872	eval-mlogloss:0.08655
[159]	train-mlogloss:0.14864	eval-mlogloss:0.08655
[160]	train-mlogloss:0.14858	eval-mlogloss:0.08655
[161]	train-mlogloss:0.14853	eval-mlogloss:0.08654

[I 2025-09-14 02:40:05,674] Trial 1 finished with value: 1.0 and parameters: {'lambda': 2.9410724283205743e-08, 'alpha': 3.716479641474016e-05, 'eta': 0.18529849999045672, 'gamma': 0.00041824437326498274, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.898329432056787, 'colsample_bytree': 0.7470722684104807}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.86532	eval-mlogloss:0.86275

[I 2025-09-14 02:40:05,683] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.95426	eval-mlogloss:0.97008
[1]	train-mlogloss:0.70380	eval-mlogloss:0.70682

[I 2025-09-14 02:40:05,696] Trial 3 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02068	eval-mlogloss:1.01653
[1]	train-mlogloss:0.95540	eval-mlogloss:0.94987
[2]	train-mlogloss:0.89131	eval-mlogloss:0.88114
[3]	train-mlogloss:0.82872	eval-mlogloss:0.81576
[4]	train-mlogloss:0.77498	eval-mlogloss:0.75931
[5]	train-mlogloss:0.72334	eval-mlogloss:0.70440
[6]	train-mlogloss:0.67709	eval-mlogloss:0.65406
[7]	train-mlogloss:0.63908	eval-mlogloss:0.61770
[8]	train-mlogloss:0.60169	eval-mlogloss:0.57743
[9]	train-mlogloss:0.56683	eval-mlogloss:0.53905
[10]	train-mlogloss:0.53507	eval-mlogloss:0.50508
[11]	train-mlogloss:0.50581	eval-mlogloss:0.47313
[12]	train-mlogloss:0.47891	eval-mlogloss:0.44410
[13]	train-mlogloss:0.45459	eval-mlogloss:0.41798
[14]	train-mlogloss:0.42955	eval-mlogloss:0.39144
[15]	train-mlogloss:0.40778	eval-mlogloss:0.36779
[16]	train-mlogloss:0.38817	eval-mlogloss:0.34692
[17]	train-mlogloss:0.36923	eval-mlogloss:0.32655
[18]	train-mlogloss:0.35314	eval-mlogloss:0.31108
[19]	train-mlogloss:0.33610	eval-mlogloss:0.29363
[20]	train-mlogloss:0.32000	eval-mlogloss:0.27638
[21]	train-mlogloss:0.30971	eval-mlogloss:0.26528
[22]	train-mlogloss:0.29561	eval-mlogloss:0.24914
[23]	train-mlogloss:0.28190	eval-mlogloss:0.23462
[24]	train-mlogloss:0.26969	eval-mlogloss:0.22066
[25]	train-mlogloss:0.25947	eval-mlogloss:0.20901
[26]	train-mlogloss:0.24813	eval-mlogloss:0.19654
[27]	train-mlogloss:0.23975	eval-mlogloss:0.18642
[28]	train-mlogloss:0.23267	eval-mlogloss:0.17856
[29]	train-mlogloss:0.22456	eval-mlogloss:0.16878
[30]	train-mlogloss:0.21629	eval-mlogloss:0.15999
[31]	train-mlogloss:0.20824	eval-mlogloss:0.15129
[32]	train-mlogloss:0.20162	eval-mlogloss:0.14371
[33]	train-mlogloss:0.19573	eval-mlogloss:0.13596
[34]	train-mlogloss:0.18938	eval-mlogloss:0.12917
[35]	train-mlogloss:0.18443	eval-mlogloss:0.12357
[36]	train-mlogloss:0.17977	eval-mlogloss:0.11889
[37]	train-mlogloss:0.17581	eval-mlogloss:0.11505
[38]	train-mlogloss:0.17232	eval-mlogloss:0.11154
[39]	train-mlogloss:0.16869	eval-mlogloss:0.10731
[40]	train-mlogloss:0.16445	eval-mlogloss:0.10287
[41]	train-mlogloss:0.16334	eval-mlogloss:0.10123
[42]	train-mlogloss:0.16093	eval-mlogloss:0.09848
[43]	train-mlogloss:0.15807	eval-mlogloss:0.09511
[44]	train-mlogloss:0.15509	eval-mlogloss:0.09094
[45]	train-mlogloss:0.15267	eval-mlogloss:0.08770
[46]	train-mlogloss:0.15086	eval-mlogloss:0.08549
[47]	train-mlogloss:0.15085	eval-mlogloss:0.08550
[48]	train-mlogloss:0.14993	eval-mlogloss:0.08429
[49]	train-mlogloss:0.14836	eval-mlogloss:0.08272
[50]	train-mlogloss:0.14746	eval-mlogloss:0.08140
[51]	train-mlogloss:0.14636	eval-mlogloss:0.07984
[52]	train-mlogloss:0.14578	eval-mlogloss:0.08021
[53]	train-mlogloss:0.14551	eval-mlogloss:0.07983
[54]	train-mlogloss:0.14491	eval-mlogloss:0.07997
[55]	train-mlogloss:0.14428	eval-mlogloss:0.07899
[56]	train-mlogloss:0.14324	eval-mlogloss:0.07751
[57]	train-mlogloss:0.14326	eval-mlogloss:0.07752
[58]	train-mlogloss:0.14250	eval-mlogloss:0.07636
[59]	train-mlogloss:0.14249	eval-mlogloss:0.07637
[60]	train-mlogloss:0.14190	eval-mlogloss:0.07669
[61]	train-mlogloss:0.14150	eval-mlogloss:0.07628
[62]	train-mlogloss:0.14054	eval-mlogloss:0.07555
[63]	train-mlogloss:0.14046	eval-mlogloss:0.07529

[I 2025-09-14 02:40:05,941] Trial 4 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:1.01871	eval-mlogloss:1.01370
[1]	train-mlogloss:0.90714	eval-mlogloss:0.89721

[I 2025-09-14 02:40:05,958] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97755	eval-mlogloss:0.98045
[1]	train-mlogloss:0.73428	eval-mlogloss:0.72550

[I 2025-09-14 02:40:05,994] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84859	eval-mlogloss:0.84529

[I 2025-09-14 02:40:06,010] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.94689	eval-mlogloss:0.93533
[1]	train-mlogloss:0.75925	eval-mlogloss:0.73926

[I 2025-09-14 02:40:06,023] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01002	eval-mlogloss:1.00825

[I 2025-09-14 02:40:06,038] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09001	eval-mlogloss:1.09083
[1]	train-mlogloss:1.08086	eval-mlogloss:1.08144
[2]	train-mlogloss:1.07016	eval-mlogloss:1.07032
[3]	train-mlogloss:1.06108	eval-mlogloss:1.06075
[4]	train-mlogloss:1.04957	eval-mlogloss:1.04961
[5]	train-mlogloss:1.03785	eval-mlogloss:1.03748
[6]	train-mlogloss:1.02831	eval-mlogloss:1.02816
[7]	train-mlogloss:1.01858	eval-mlogloss:1.01799
[8]	train-mlogloss:1.01855	eval-mlogloss:1.01811
[9]	train-mlogloss:1.00986	eval-mlogloss:1.00918
[10]	train-mlogloss:1.00432	eval-mlogloss:1.00406
[11]	train-mlogloss:0.99308	eval-mlogloss:0.99167
[12]	train-mlogloss:0.98118	eval-mlogloss:0.98003
[13]	train-mlogloss:0.97667	eval-mlogloss:0.97552
[14]	train-mlogloss:0.97116	eval-mlogloss:0.96959
[15]	train-mlogloss:0.96115	eval-mlogloss:0.95917
[16]	train-mlogloss:0.95756	eval-mlogloss:0.95603
[17]	train-mlogloss:0.95033	eval-mlogloss:0.94896
[18]	train-mlogloss:0.93969	eval-mlogloss:0.93693
[19]	train-mlogloss:0.93603	eval-mlogloss:0.93303
[20]	train-mlogloss:0.92606	eval-mlogloss:0.92297
[21]	train-mlogloss:0.91678	eval-mlogloss:0.91320
[22]	train-mlogloss:0.91012	eval-mlogloss:0.90505
[23]	train-mlogloss:0.89986	eval-mlogloss:0.89402
[24]	train-mlogloss:0.89044	eval-mlogloss:0.88383
[25]	train-mlogloss:0.88226	eval-mlogloss:0.87514
[26]	train-mlogloss:0.87225	eval-mlogloss:0.86488
[27]	train-mlogloss:0.87224	eval-mlogloss:0.86493
[28]	train-mlogloss:0.86747	eval-mlogloss:0.86071
[29]	train-mlogloss:0.86012	eval-mlogloss:0.85247
[30]	train-mlogloss:0.85481	eval-mlogloss:0.84696
[31]	train-mlogloss:0.84546	eval-mlogloss:0.83748
[32]	train-mlogloss:0.84473	eval-mlogloss:0.83661
[33]	train-mlogloss:0.83600	eval-mlogloss:0.82632
[34]	train-mlogloss:0.83193	eval-mlogloss:0.82264
[35]	train-mlogloss:0.82936	eval-mlogloss:0.81987
[36]	train-mlogloss:0.82125	eval-mlogloss:0.81170
[37]	train-mlogloss:0.81440	eval-mlogloss:0.80461
[38]	train-mlogloss:0.81141	eval-mlogloss:0.80165
[39]	train-mlogloss:0.80602	eval-mlogloss:0.79615
[40]	train-mlogloss:0.80208	eval-mlogloss:0.79229
[41]	train-mlogloss:0.80117	eval-mlogloss:0.79077
[42]	train-mlogloss:0.79922	eval-mlogloss:0.78844
[43]	train-mlogloss:0.79438	eval-mlogloss:0.78368
[44]	train-mlogloss:0.78984	eval-mlogloss:0.77914
[45]	train-mlogloss:0.78953	eval-mlogloss:0.77878
[46]	train-mlogloss:0.78500	eval-mlogloss:0.77429
[47]	train-mlogloss:0.78490	eval-mlogloss:0.77448
[48]	train-mlogloss:0.77809	eval-mlogloss:0.76737
[49]	train-mlogloss:0.77505	eval-mlogloss:0.76496
[50]	train-mlogloss:0.77087	eval-mlogloss:0.75993
[51]	train-mlogloss:0.76474	eval-mlogloss:0.75380
[52]	train-mlogloss:0.76232	eval-mlogloss:0.75141
[53]	train-mlogloss:0.75968	eval-mlogloss:0.74840
[54]	train-mlogloss:0.75163	eval-mlogloss:0.74062
[55]	train-mlogloss:0.74722	eval-mlogloss:0.73633
[56]	train-mlogloss:0.74656	eval-mlogloss:0.73556
[57]	train-mlogloss:0.74593	eval-mlogloss:0.73496
[58]	train-mlogloss:0.74230	eval-mlogloss:0.73091
[59]	train-mlogloss:0.73946	eval-mlogloss:0.72766
[60]	train-mlogloss:0.73945	eval-mlogloss:0.72767
[61]	train-mlogloss:0.73647	eval-mlogloss:0.72492
[62]	train-mlogloss:0.73266	eval-mlogloss:0.72110
[63]	train-mlogloss:0.73259	eval-mlogloss:0.72104
[64]	train-mlogloss:0.73164	eval-mlogloss:0.72007
[65]	train-mlogloss:0.72845	eval-mlogloss:0.71743
[66]	train-mlogloss:0.72792	eval-mlogloss:0.71696
[67]	train-mlogloss:0.72716	eval-mlogloss:0.71648
[68]	train-mlogloss:0.72334	eval-mlogloss:0.71262
[69]	train-mlogloss:0.72255	eval-mlogloss:0.71137
[70]	train-mlogloss:0.72255	eval-mlogloss:0.71135
[71]	train-mlogloss:0.71941	eval-mlogloss:0.70790
[72]	train-mlogloss:0.71934	eval-mlogloss:0.70790
[73]	train-mlogloss:0.71249	eval-mlogloss:0.70071
[74]	train-mlogloss:0.70878	eval-mlogloss:0.69752
[75]	train-mlogloss:0.70864	eval-mlogloss:0.69743
[76]	train-mlogloss:0.70451	eval-mlogloss:0.69309
[77]	train-mlogloss:0.70400	eval-mlogloss:0.69213
[78]	train-mlogloss:0.70148	eval-mlogloss:0.68956
[79]	train-mlogloss:0.70146	eval-mlogloss:0.68960
[80]	train-mlogloss:0.69926	eval-mlogloss:0.68747
[81]	train-mlogloss:0.69588	eval-mlogloss:0.68377
[82]	train-mlogloss:0.69326	eval-mlogloss:0.68099
[83]	train-mlogloss:0.69332	eval-mlogloss:0.68080
[84]	train-mlogloss:0.69049	eval-mlogloss:0.67770
[85]	train-mlogloss:0.69050	eval-mlogloss:0.67770
[86]	train-mlogloss:0.69041	eval-mlogloss:0.67776
[87]	train-mlogloss:0.69041	eval-mlogloss:0.67773
[88]	train-mlogloss:0.68984	eval-mlogloss:0.67719
[89]	train-mlogloss:0.68673	eval-mlogloss:0.67370
[90]	train-mlogloss:0.68448	eval-mlogloss:0.67121
[91]	train-mlogloss:0.68108	eval-mlogloss:0.66782
[92]	train-mlogloss:0.68021	eval-mlogloss:0.66691
[93]	train-mlogloss:0.67922	eval-mlogloss:0.66509
[94]	train-mlogloss:0.67907	eval-mlogloss:0.66508
[95]	train-mlogloss:0.67906	eval-mlogloss:0.66518
[96]	train-mlogloss:0.67899	eval-mlogloss:0.66513
[97]	train-mlogloss:0.67893	eval-mlogloss:0.66525
[98]	train-mlogloss:0.67869	eval-mlogloss:0.66497
[99]	train-mlogloss:0.67504	eval-mlogloss:0.66031
[100]	train-mlogloss:0.67449	eval-mlogloss:0.65975
[101]	train-mlogloss:0.67083	eval-mlogloss:0.65626
[102]	train-mlogloss:0.67049	eval-mlogloss:0.65597
[103]	train-mlogloss:0.67039	eval-mlogloss:0.65593
[104]	train-mlogloss:0.67003	eval-mlogloss:0.65557
[105]	train-mlogloss:0.66933	eval-mlogloss:0.65441
[106]	train-mlogloss:0.66692	eval-mlogloss:0.65191
[107]	train-mlogloss:0.66507	eval-mlogloss:0.65018
[108]	train-mlogloss:0.66470	eval-mlogloss:0.64963
[109]	train-mlogloss:0.66355	eval-mlogloss:0.64847
[110]	train-mlogloss:0.66181	eval-mlogloss:0.64672
[111]	train-mlogloss:0.65911	eval-mlogloss:0.64311
[112]	train-mlogloss:0.65552	eval-mlogloss:0.63896
[113]	train-mlogloss:0.65483	eval-mlogloss:0.63788
[114]	train-mlogloss:0.65285	eval-mlogloss:0.63608
[115]	train-mlogloss:0.65228	eval-mlogloss:0.63557
[116]	train-mlogloss:0.65228	eval-mlogloss:0.63560
[117]	train-mlogloss:0.65187	eval-mlogloss:0.63514
[118]	train-mlogloss:0.65187	eval-mlogloss:0.63505
[119]	train-mlogloss:0.64842	eval-mlogloss:0.63165
[120]	train-mlogloss:0.64508	eval-mlogloss:0.62794
[121]	train-mlogloss:0.64472	eval-mlogloss:0.62763
[122]	train-mlogloss:0.64260	eval-mlogloss:0.62557
[123]	train-mlogloss:0.64205	eval-mlogloss:0.62509
[124]	train-mlogloss:0.63876	eval-mlogloss:0.62138
[125]	train-mlogloss:0.63814	eval-mlogloss:0.62089
[126]	train-mlogloss:0.63754	eval-mlogloss:0.61979
[127]	train-mlogloss:0.63697	eval-mlogloss:0.61862
[128]	train-mlogloss:0.63624	eval-mlogloss:0.61711
[129]	train-mlogloss:0.63320	eval-mlogloss:0.61374
[130]	train-mlogloss:0.63267	eval-mlogloss:0.61274
[131]	train-mlogloss:0.63268	eval-mlogloss:0.61285
[132]	train-mlogloss:0.62719	eval-mlogloss:0.60670
[133]	train-mlogloss:0.62719	eval-mlogloss:0.60662
[134]	train-mlogloss:0.62719	eval-mlogloss:0.60658
[135]	train-mlogloss:0.62392	eval-mlogloss:0.60343
[136]	train-mlogloss:0.62325	eval-mlogloss:0.60249
[137]	train-mlogloss:0.62024	eval-mlogloss:0.59943
[138]	train-mlogloss:0.61979	eval-mlogloss:0.59864
[139]	train-mlogloss:0.61981	eval-mlogloss:0.59865
[140]	train-mlogloss:0.61984	eval-mlogloss:0.59855
[141]	train-mlogloss:0.61979	eval-mlogloss:0.59856
[142]	train-mlogloss:0.61675	eval-mlogloss:0.59564
[143]	train-mlogloss:0.61666	eval-mlogloss:0.59578
[144]	train-mlogloss:0.61662	eval-mlogloss:0.59581
[145]	train-mlogloss:0.61609	eval-mlogloss:0.59534
[146]	train-mlogloss:0.61610	eval-mlogloss:0.59518
[147]	train-mlogloss:0.61493	eval-mlogloss:0.59389
[148]	train-mlogloss:0.61298	eval-mlogloss:0.59234
[149]	train-mlogloss:0.61299	eval-mlogloss:0.59239
[150]	train-mlogloss:0.61299	eval-mlogloss:0.59233
[151]	train-mlogloss:0.61299	eval-mlogloss:0.59232
[152]	train-mlogloss:0.61299	eval-mlogloss:0.59224
[153]	train-mlogloss:0.61037	eval-mlogloss:0.58924
[154]	train-mlogloss:0.60971	eval-mlogloss:0.58872
[155]	train-mlogloss:0.60962	eval-mlogloss:0.58865
[156]	train-mlogloss:0.60963	eval-mlogloss:0.58870
[157]	train-mlogloss:0.60959	eval-mlogloss:0.58854
[158]	train-mlogloss:0.60956	eval-mlogloss:0.58857
[159]	train-mlogloss:0.60953	eval-mlogloss:0.58854
[160]	train-mlogloss:0.60950	eval-mlogloss:0.58852
[161]	train-mlogloss:0.60935	eval-mlogloss:0.58845
[162]	train-mlogloss:0.60933	eval-mlogloss:0.58842
[163]	train-mlogloss:0.60933	eval-mlogloss:0.58835
[164]	train-mlogloss:0.60853	eval-mlogloss:0.58680
[165]	train-mlogloss:0.60847	eval-mlogloss:0.58675
[166]	train-mlogloss:0.60497	eval-mlogloss:0.58275
[167]	train-mlogloss:0.60498	eval-mlogloss:0.58272
[168]	train-mlogloss:0.60499	eval-mlogloss:0.58272
[169]	train-mlogloss:0.60374	eval-mlogloss:0.58071
[170]	train-mlogloss:0.60372	eval-mlogloss:0.58079
[171]	train-mlogloss:0.60318	eval-mlogloss:0.57984
[172]	train-mlogloss:0.60286	eval-mlogloss:0.57916
[173]	train-mlogloss:0.60286	eval-mlogloss:0.57912
[174]	train-mlogloss:0.60281	eval-mlogloss:0.57912
[175]	train-mlogloss:0.60031	eval-mlogloss:0.57609
[176]	train-mlogloss:0.60032	eval-mlogloss:0.57611
[177]	train-mlogloss:0.60027	eval-mlogloss:0.57605
[178]	train-mlogloss:0.60026	eval-mlogloss:0.57597
[179]	train-mlogloss:0.60030	eval-mlogloss:0.57603
[180]	train-mlogloss:0.60011	eval-mlogloss:0.57583
[181]	train-mlogloss:0.60009	eval-mlogloss:0.57576
[182]	train-mlogloss:0.60009	eval-mlogloss:0.57570
[183]	train-mlogloss:0.60003	eval-mlogloss:0.57580
[184]	train-mlogloss:0.59943	eval-mlogloss:0.57458
[185]	train-mlogloss:0.59943	eval-mlogloss:0.57465
[186]	train-mlogloss:0.59900	eval-mlogloss:0.57369
[187]	train-mlogloss:0.59901	eval-mlogloss:0.57364
[188]	train-mlogloss:0.59899	eval-mlogloss:0.57371
[189]	train-mlogloss:0.59867	eval-mlogloss:0.57316
[190]	train-mlogloss:0.59861	eval-mlogloss:0.57322
[191]	train-mlogloss:0.59862	eval-mlogloss:0.57323
[192]	train-mlogloss:0.59860	eval-mlogloss:0.57324
[193]	train-mlogloss:0.59854	eval-mlogloss:0.57316
[194]	train-mlogloss:0.59546	eval-mlogloss:0.57048
[195]	train-mlogloss:0.59548	eval-mlogloss:0.57044
[196]	train-mlogloss:0.59539	eval-mlogloss:0.57053
[197]	train-mlogloss:0.59539	eval-mlogloss:0.57049
[198]	train-mlogloss:0.59541	eval-mlogloss:0.57041
[199]	train-mlogloss:0.59277	eval-mlogloss:0.56743
[200]	train-mlogloss:0.59277	eval-mlogloss:0.56742
[201]	train-mlogloss:0.58836	eval-mlogloss:0.56267
[202]	train-mlogloss:0.58832	eval-mlogloss:0.56261
[203]	train-mlogloss:0.58828	eval-mlogloss:0.56267
[204]	train-mlogloss:0.58828	eval-mlogloss:0.56270
[205]	train-mlogloss:0.58801	eval-mlogloss:0.56244
[206]	train-mlogloss:0.58735	eval-mlogloss:0.56203
[207]	train-mlogloss:0.58729	eval-mlogloss:0.56207
[208]	train-mlogloss:0.58634	eval-mlogloss:0.56101
[209]	train-mlogloss:0.58639	eval-mlogloss:0.56096
[210]	train-mlogloss:0.58640	eval-mlogloss:0.56101
[211]	train-mlogloss:0.58625	eval-mlogloss:0.56082
[212]	train-mlogloss:0.58629	eval-mlogloss:0.56092
[213]	train-mlogloss:0.58604	eval-mlogloss:0.56060
[214]	train-mlogloss:0.58583	eval-mlogloss:0.56028
[215]	train-mlogloss:0.58562	eval-mlogloss:0.56021
[216]	train-mlogloss:0.58563	eval-mlogloss:0.56015
[217]	train-mlogloss:0.58556	eval-mlogloss:0.56023
[218]	train-mlogloss:0.58522	eval-mlogloss:0.55967
[219]	train-mlogloss:0.58219	eval-mlogloss:0.55693
[220]	train-mlogloss:0.58220	eval-mlogloss:0.55690
[221]	train-mlogloss:0.58020	eval-mlogloss:0.55513
[222]	train-mlogloss:0.58022	eval-mlogloss:0.55513
[223]	train-mlogloss:0.58019	eval-mlogloss:0.55515
[224]	train-mlogloss:0.58006	eval-mlogloss:0.55512
[225]	train-mlogloss:0.57758	eval-mlogloss:0.55229
[226]	train-mlogloss:0.57500	eval-mlogloss:0.54891
[227]	train-mlogloss:0.57499	eval-mlogloss:0.54893
[228]	train-mlogloss:0.57500	eval-mlogloss:0.54887
[229]	train-mlogloss:0.57500	eval-mlogloss:0.54902
[230]	train-mlogloss:0.57443	eval-mlogloss:0.54788
[231]	train-mlogloss:0.57446	eval-mlogloss:0.54795
[232]	train-mlogloss:0.57445	eval-mlogloss:0.54798
[233]	train-mlogloss:0.57447	eval-mlogloss:0.54791
[234]	train-mlogloss:0.57447	eval-mlogloss:0.54797
[235]	train-mlogloss:0.57445	eval-mlogloss:0.54804
[236]	train-mlogloss:0.57430	eval-mlogloss:0.54798
[237]	train-mlogloss:0.57430	eval-mlogloss:0.54800
[238]	train-mlogloss:0.57420	eval-mlogloss:0.54786
[239]	train-mlogloss:0.57407	eval-mlogloss:0.54782
[240]	train-mlogloss:0.57328	eval-mlogloss:0.54625
[241]	train-mlogloss:0.57242	eval-mlogloss:0.54522
[242]	train-mlogloss:0.57244	eval-mlogloss:0.54534
[243]	train-mlogloss:0.57243	eval-mlogloss:0.54530
[244]	train-mlogloss:0.57243	eval-mlogloss:0.54530
[245]	train-mlogloss:0.57215	eval-mlogloss:0.54512
[246]	train-mlogloss:0.57215	eval-mlogloss:0.54494
[247]	train-mlogloss:0.57059	eval-mlogloss:0.54319
[248]	train-mlogloss:0.57060	eval-mlogloss:0.54319
[249]	train-mlogloss:0.57060	eval-mlogloss:0.54303
[250]	train-mlogloss:0.57056	eval-mlogloss:0.54296
[251]	train-mlogloss:0.57060	eval-mlogloss:0.54291
[252]	train-mlogloss:0.57033	eval-mlogloss:0.54260
[253]	train-mlogloss:0.57009	eval-mlogloss:0.54238
[254]	train-mlogloss:0.57009	eval-mlogloss:0.54244
[255]	train-mlogloss:0.57008	eval-mlogloss:0.54249
[256]	train-mlogloss:0.56968	eval-mlogloss:0.54201
[257]	train-mlogloss:0.56965	eval-mlogloss:0.54195
[258]	train-mlogloss:0.56959	eval-mlogloss:0.54179
[259]	train-mlogloss:0.56697	eval-mlogloss:0.53865
[260]	train-mlogloss:0.56698	eval-mlogloss:0.53857
[261]	train-mlogloss:0.56697	eval-mlogloss:0.53856
[262]	train-mlogloss:0.56644	eval-mlogloss:0.53745
[263]	train-mlogloss:0.56641	eval-mlogloss:0.53748
[264]	train-mlogloss:0.56641	eval-mlogloss:0.53745
[265]	train-mlogloss:0.56641	eval-mlogloss:0.53746
[266]	train-mlogloss:0.56639	eval-mlogloss:0.53746
[267]	train-mlogloss:0.56634	eval-mlogloss:0.53745
[268]	train-mlogloss:0.56583	eval-mlogloss:0.53712
[269]	train-mlogloss:0.56555	eval-mlogloss:0.53658
[270]	train-mlogloss:0.56512	eval-mlogloss:0.53558
[271]	train-mlogloss:0.56510	eval-mlogloss:0.53562
[272]	train-mlogloss:0.56506	eval-mlogloss:0.53557
[273]	train-mlogloss:0.56507	eval-mlogloss:0.53566
[274]	train-mlogloss:0.56507	eval-mlogloss:0.53575
[275]	train-mlogloss:0.56508	eval-mlogloss:0.53574
[276]	train-mlogloss:0.56508	eval-mlogloss:0.53575
[277]	train-mlogloss:0.56475	eval-mlogloss:0.53546
[278]	train-mlogloss:0.56319	eval-mlogloss:0.53394
[279]	train-mlogloss:0.56320	eval-mlogloss:0.53396
[280]	train-mlogloss:0.56322	eval-mlogloss:0.53381
[281]	train-mlogloss:0.56322	eval-mlogloss:0.53380
[282]	train-mlogloss:0.56290	eval-mlogloss:0.53344
[283]	train-mlogloss:0.56287	eval-mlogloss:0.53343
[284]	train-mlogloss:0.56286	eval-mlogloss:0.53345
[285]	train-mlogloss:0.56284	eval-mlogloss:0.53353
[286]	train-mlogloss:0.56278	eval-mlogloss:0.53362
[287]	train-mlogloss:0.56060	eval-mlogloss:0.53096
[288]	train-mlogloss:0.56059	eval-mlogloss:0.53094
[289]	train-mlogloss:0.56031	eval-mlogloss:0.53061
[290]	train-mlogloss:0.56021	eval-mlogloss:0.53051
[291]	train-mlogloss:0.56022	eval-mlogloss:0.53059
[292]	train-mlogloss:0.56021	eval-mlogloss:0.53067
[293]	train-mlogloss:0.56021	eval-mlogloss:0.53067
[294]	train-mlogloss:0.56013	eval-mlogloss:0.53060
[295]	train-mlogloss:0.56014	eval-mlogloss:0.53051
[296]	train-mlogloss:0.56012	eval-mlogloss:0.53051
[297]	train-mlogloss:0.56011	eval-mlogloss:0.53056
[298]	train-mlogloss:0.56011	eval-mlogloss:0.53063
[299]	train-mlogloss:0.56011	eval-mlogloss:0.53056

[I 2025-09-14 02:40:09,470] Trial 10 finished with value: 0.9666666666666667 and parameters: {'lambda': 0.16720220248417192, 'alpha': 0.011283765135160743, 'eta': 0.017304229639267116, 'gamma': 1.3954281698442756e-05, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.4085361116311337, 'colsample_bytree': 0.9927070505080676}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.85895	eval-mlogloss:0.84015
[1]	train-mlogloss:0.68832	eval-mlogloss:0.66560

[I 2025-09-14 02:40:09,503] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87373	eval-mlogloss:0.85896

[I 2025-09-14 02:40:09,533] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99463	eval-mlogloss:0.99778

[I 2025-09-14 02:40:09,565] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89316	eval-mlogloss:0.89618

[I 2025-09-14 02:40:09,634] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96691	eval-mlogloss:0.95707

[I 2025-09-14 02:40:09,740] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83789	eval-mlogloss:0.82073
[1]	train-mlogloss:0.66021	eval-mlogloss:0.62770

[I 2025-09-14 02:40:09,832] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99690	eval-mlogloss:0.98631

[I 2025-09-14 02:40:09,923] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.95872	eval-mlogloss:0.97687
[1]	train-mlogloss:0.68111	eval-mlogloss:0.68040

[I 2025-09-14 02:40:10,129] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87678	eval-mlogloss:0.87452

[I 2025-09-14 02:40:10,236] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92047	eval-mlogloss:0.91801

[I 2025-09-14 02:40:10,422] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09320	eval-mlogloss:1.09383
[1]	train-mlogloss:1.08966	eval-mlogloss:1.09063
[2]	train-mlogloss:1.08246	eval-mlogloss:1.08314
[3]	train-mlogloss:1.07884	eval-mlogloss:1.07921
[4]	train-mlogloss:1.07123	eval-mlogloss:1.07177
[5]	train-mlogloss:1.06433	eval-mlogloss:1.06476
[6]	train-mlogloss:1.05767	eval-mlogloss:1.05824
[7]	train-mlogloss:1.05128	eval-mlogloss:1.05170
[8]	train-mlogloss:1.05126	eval-mlogloss:1.05179
[9]	train-mlogloss:1.04508	eval-mlogloss:1.04544
[10]	train-mlogloss:1.04125	eval-mlogloss:1.04180
[11]	train-mlogloss:1.03359	eval-mlogloss:1.03370
[12]	train-mlogloss:1.02508	eval-mlogloss:1.02535
[13]	train-mlogloss:1.02178	eval-mlogloss:1.02202
[14]	train-mlogloss:1.01820	eval-mlogloss:1.01824
[15]	train-mlogloss:1.01062	eval-mlogloss:1.01051
[16]	train-mlogloss:1.00797	eval-mlogloss:1.00816
[17]	train-mlogloss:1.00320	eval-mlogloss:1.00378
[18]	train-mlogloss:0.99630	eval-mlogloss:0.99620
[19]	train-mlogloss:0.99356	eval-mlogloss:0.99327
[20]	train-mlogloss:0.98564	eval-mlogloss:0.98559
[21]	train-mlogloss:0.97992	eval-mlogloss:0.97947
[22]	train-mlogloss:0.97598	eval-mlogloss:0.97543
[23]	train-mlogloss:0.96923	eval-mlogloss:0.96831
[24]	train-mlogloss:0.96205	eval-mlogloss:0.96058
[25]	train-mlogloss:0.95574	eval-mlogloss:0.95388
[26]	train-mlogloss:0.94852	eval-mlogloss:0.94624
[27]	train-mlogloss:0.94851	eval-mlogloss:0.94628
[28]	train-mlogloss:0.94783	eval-mlogloss:0.94545
[29]	train-mlogloss:0.94263	eval-mlogloss:0.94005
[30]	train-mlogloss:0.93683	eval-mlogloss:0.93368
[31]	train-mlogloss:0.92942	eval-mlogloss:0.92613
[32]	train-mlogloss:0.92711	eval-mlogloss:0.92360
[33]	train-mlogloss:0.92103	eval-mlogloss:0.91685
[34]	train-mlogloss:0.91808	eval-mlogloss:0.91366
[35]	train-mlogloss:0.91599	eval-mlogloss:0.91142
[36]	train-mlogloss:0.90955	eval-mlogloss:0.90487
[37]	train-mlogloss:0.90402	eval-mlogloss:0.89915
[38]	train-mlogloss:0.90001	eval-mlogloss:0.89505
[39]	train-mlogloss:0.89733	eval-mlogloss:0.89277
[40]	train-mlogloss:0.89239	eval-mlogloss:0.88769
[41]	train-mlogloss:0.88967	eval-mlogloss:0.88435
[42]	train-mlogloss:0.88564	eval-mlogloss:0.88007
[43]	train-mlogloss:0.88181	eval-mlogloss:0.87626
[44]	train-mlogloss:0.87817	eval-mlogloss:0.87260
[45]	train-mlogloss:0.87814	eval-mlogloss:0.87269
[46]	train-mlogloss:0.87452	eval-mlogloss:0.86904
[47]	train-mlogloss:0.87324	eval-mlogloss:0.86800
[48]	train-mlogloss:0.86781	eval-mlogloss:0.86234
[49]	train-mlogloss:0.86272	eval-mlogloss:0.85754
[50]	train-mlogloss:0.85949	eval-mlogloss:0.85368
[51]	train-mlogloss:0.85469	eval-mlogloss:0.84853
[52]	train-mlogloss:0.85273	eval-mlogloss:0.84659
[53]	train-mlogloss:0.85058	eval-mlogloss:0.84418
[54]	train-mlogloss:0.84396	eval-mlogloss:0.83731
[55]	train-mlogloss:0.83766	eval-mlogloss:0.83074
[56]	train-mlogloss:0.83561	eval-mlogloss:0.82823
[57]	train-mlogloss:0.83346	eval-mlogloss:0.82601
[58]	train-mlogloss:0.82919	eval-mlogloss:0.82145
[59]	train-mlogloss:0.82700	eval-mlogloss:0.81904
[60]	train-mlogloss:0.82543	eval-mlogloss:0.81734
[61]	train-mlogloss:0.82312	eval-mlogloss:0.81517
[62]	train-mlogloss:0.81955	eval-mlogloss:0.81150
[63]	train-mlogloss:0.81944	eval-mlogloss:0.81146
[64]	train-mlogloss:0.81860	eval-mlogloss:0.81063
[65]	train-mlogloss:0.81565	eval-mlogloss:0.80838
[66]	train-mlogloss:0.81553	eval-mlogloss:0.80849
[67]	train-mlogloss:0.81500	eval-mlogloss:0.80816
[68]	train-mlogloss:0.81194	eval-mlogloss:0.80505
[69]	train-mlogloss:0.81006	eval-mlogloss:0.80300
[70]	train-mlogloss:0.80794	eval-mlogloss:0.80106
[71]	train-mlogloss:0.80562	eval-mlogloss:0.79862
[72]	train-mlogloss:0.80556	eval-mlogloss:0.79862
[73]	train-mlogloss:0.79986	eval-mlogloss:0.79265
[74]	train-mlogloss:0.79724	eval-mlogloss:0.79049
[75]	train-mlogloss:0.79647	eval-mlogloss:0.78964
[76]	train-mlogloss:0.79314	eval-mlogloss:0.78609
[77]	train-mlogloss:0.79042	eval-mlogloss:0.78354
[78]	train-mlogloss:0.78837	eval-mlogloss:0.78145
[79]	train-mlogloss:0.78658	eval-mlogloss:0.77998
[80]	train-mlogloss:0.78479	eval-mlogloss:0.77825
[81]	train-mlogloss:0.78197	eval-mlogloss:0.77517
[82]	train-mlogloss:0.77990	eval-mlogloss:0.77298
[83]	train-mlogloss:0.77752	eval-mlogloss:0.77009
[84]	train-mlogloss:0.77560	eval-mlogloss:0.76819
[85]	train-mlogloss:0.77561	eval-mlogloss:0.76818
[86]	train-mlogloss:0.77554	eval-mlogloss:0.76822
[87]	train-mlogloss:0.77554	eval-mlogloss:0.76818
[88]	train-mlogloss:0.77140	eval-mlogloss:0.76435
[89]	train-mlogloss:0.76897	eval-mlogloss:0.76166
[90]	train-mlogloss:0.76759	eval-mlogloss:0.76043
[91]	train-mlogloss:0.76475	eval-mlogloss:0.75762
[92]	train-mlogloss:0.76179	eval-mlogloss:0.75444
[93]	train-mlogloss:0.75972	eval-mlogloss:0.75166
[94]	train-mlogloss:0.75959	eval-mlogloss:0.75163
[95]	train-mlogloss:0.75958	eval-mlogloss:0.75170
[96]	train-mlogloss:0.75953	eval-mlogloss:0.75157
[97]	train-mlogloss:0.75915	eval-mlogloss:0.75125
[98]	train-mlogloss:0.75560	eval-mlogloss:0.74740
[99]	train-mlogloss:0.75133	eval-mlogloss:0.74217
[100]	train-mlogloss:0.74862	eval-mlogloss:0.73927
[101]	train-mlogloss:0.74407	eval-mlogloss:0.73473
[102]	train-mlogloss:0.74371	eval-mlogloss:0.73428
[103]	train-mlogloss:0.74211	eval-mlogloss:0.73266
[104]	train-mlogloss:0.74137	eval-mlogloss:0.73186
[105]	train-mlogloss:0.74006	eval-mlogloss:0.73071
[106]	train-mlogloss:0.73827	eval-mlogloss:0.72889
[107]	train-mlogloss:0.73672	eval-mlogloss:0.72742
[108]	train-mlogloss:0.73673	eval-mlogloss:0.72731
[109]	train-mlogloss:0.73567	eval-mlogloss:0.72605
[110]	train-mlogloss:0.73410	eval-mlogloss:0.72431
[111]	train-mlogloss:0.73242	eval-mlogloss:0.72237
[112]	train-mlogloss:0.72970	eval-mlogloss:0.71925
[113]	train-mlogloss:0.72971	eval-mlogloss:0.71927
[114]	train-mlogloss:0.72831	eval-mlogloss:0.71777
[115]	train-mlogloss:0.72788	eval-mlogloss:0.71741
[116]	train-mlogloss:0.72788	eval-mlogloss:0.71743
[117]	train-mlogloss:0.72626	eval-mlogloss:0.71584
[118]	train-mlogloss:0.72627	eval-mlogloss:0.71576
[119]	train-mlogloss:0.72279	eval-mlogloss:0.71202
[120]	train-mlogloss:0.72021	eval-mlogloss:0.70918
[121]	train-mlogloss:0.71982	eval-mlogloss:0.70870
[122]	train-mlogloss:0.71812	eval-mlogloss:0.70705
[123]	train-mlogloss:0.71762	eval-mlogloss:0.70660
[124]	train-mlogloss:0.71501	eval-mlogloss:0.70369
[125]	train-mlogloss:0.71454	eval-mlogloss:0.70334
[126]	train-mlogloss:0.71385	eval-mlogloss:0.70265
[127]	train-mlogloss:0.71333	eval-mlogloss:0.70165
[128]	train-mlogloss:0.71269	eval-mlogloss:0.70042
[129]	train-mlogloss:0.70999	eval-mlogloss:0.69736
[130]	train-mlogloss:0.70954	eval-mlogloss:0.69657
[131]	train-mlogloss:0.70953	eval-mlogloss:0.69663
[132]	train-mlogloss:0.70518	eval-mlogloss:0.69178
[133]	train-mlogloss:0.70439	eval-mlogloss:0.69049
[134]	train-mlogloss:0.70440	eval-mlogloss:0.69046
[135]	train-mlogloss:0.70071	eval-mlogloss:0.68674
[136]	train-mlogloss:0.69942	eval-mlogloss:0.68534
[137]	train-mlogloss:0.69700	eval-mlogloss:0.68286
[138]	train-mlogloss:0.69695	eval-mlogloss:0.68283
[139]	train-mlogloss:0.69637	eval-mlogloss:0.68202
[140]	train-mlogloss:0.69620	eval-mlogloss:0.68190
[141]	train-mlogloss:0.69616	eval-mlogloss:0.68190
[142]	train-mlogloss:0.69370	eval-mlogloss:0.67948
[143]	train-mlogloss:0.69053	eval-mlogloss:0.67627
[144]	train-mlogloss:0.69051	eval-mlogloss:0.67631
[145]	train-mlogloss:0.68832	eval-mlogloss:0.67409
[146]	train-mlogloss:0.68833	eval-mlogloss:0.67399
[147]	train-mlogloss:0.68731	eval-mlogloss:0.67286
[148]	train-mlogloss:0.68559	eval-mlogloss:0.67122
[149]	train-mlogloss:0.68560	eval-mlogloss:0.67124
[150]	train-mlogloss:0.68324	eval-mlogloss:0.66894
[151]	train-mlogloss:0.68324	eval-mlogloss:0.66892
[152]	train-mlogloss:0.68325	eval-mlogloss:0.66885
[153]	train-mlogloss:0.68121	eval-mlogloss:0.66655
[154]	train-mlogloss:0.67840	eval-mlogloss:0.66387
[155]	train-mlogloss:0.67793	eval-mlogloss:0.66339
[156]	train-mlogloss:0.67794	eval-mlogloss:0.66340
[157]	train-mlogloss:0.67740	eval-mlogloss:0.66278
[158]	train-mlogloss:0.67733	eval-mlogloss:0.66278
[159]	train-mlogloss:0.67731	eval-mlogloss:0.66278
[160]	train-mlogloss:0.67728	eval-mlogloss:0.66275
[161]	train-mlogloss:0.67716	eval-mlogloss:0.66270
[162]	train-mlogloss:0.67715	eval-mlogloss:0.66267
[163]	train-mlogloss:0.67715	eval-mlogloss:0.66263
[164]	train-mlogloss:0.67644	eval-mlogloss:0.66134
[165]	train-mlogloss:0.67643	eval-mlogloss:0.66130
[166]	train-mlogloss:0.67524	eval-mlogloss:0.65984
[167]	train-mlogloss:0.67524	eval-mlogloss:0.65982
[168]	train-mlogloss:0.67311	eval-mlogloss:0.65726
[169]	train-mlogloss:0.67078	eval-mlogloss:0.65452
[170]	train-mlogloss:0.66947	eval-mlogloss:0.65317
[171]	train-mlogloss:0.66897	eval-mlogloss:0.65234
[172]	train-mlogloss:0.66868	eval-mlogloss:0.65179
[173]	train-mlogloss:0.66868	eval-mlogloss:0.65176
[174]	train-mlogloss:0.66865	eval-mlogloss:0.65175
[175]	train-mlogloss:0.66672	eval-mlogloss:0.64944
[176]	train-mlogloss:0.66649	eval-mlogloss:0.64921
[177]	train-mlogloss:0.66429	eval-mlogloss:0.64698
[178]	train-mlogloss:0.66429	eval-mlogloss:0.64693
[179]	train-mlogloss:0.66431	eval-mlogloss:0.64697
[180]	train-mlogloss:0.66418	eval-mlogloss:0.64682
[181]	train-mlogloss:0.66417	eval-mlogloss:0.64678
[182]	train-mlogloss:0.66417	eval-mlogloss:0.64674
[183]	train-mlogloss:0.66262	eval-mlogloss:0.64532
[184]	train-mlogloss:0.66038	eval-mlogloss:0.64257
[185]	train-mlogloss:0.66036	eval-mlogloss:0.64259
[186]	train-mlogloss:0.65996	eval-mlogloss:0.64177
[187]	train-mlogloss:0.65997	eval-mlogloss:0.64174
[188]	train-mlogloss:0.65995	eval-mlogloss:0.64179
[189]	train-mlogloss:0.65963	eval-mlogloss:0.64126
[190]	train-mlogloss:0.65960	eval-mlogloss:0.64131
[191]	train-mlogloss:0.65961	eval-mlogloss:0.64132
[192]	train-mlogloss:0.65959	eval-mlogloss:0.64133
[193]	train-mlogloss:0.65953	eval-mlogloss:0.64127
[194]	train-mlogloss:0.65734	eval-mlogloss:0.63931
[195]	train-mlogloss:0.65545	eval-mlogloss:0.63737
[196]	train-mlogloss:0.65539	eval-mlogloss:0.63744
[197]	train-mlogloss:0.65538	eval-mlogloss:0.63743
[198]	train-mlogloss:0.65540	eval-mlogloss:0.63739
[199]	train-mlogloss:0.65335	eval-mlogloss:0.63511
[200]	train-mlogloss:0.65336	eval-mlogloss:0.63509
[201]	train-mlogloss:0.64994	eval-mlogloss:0.63145
[202]	train-mlogloss:0.64987	eval-mlogloss:0.63135
[203]	train-mlogloss:0.64959	eval-mlogloss:0.63110
[204]	train-mlogloss:0.64955	eval-mlogloss:0.63107
[205]	train-mlogloss:0.64956	eval-mlogloss:0.63107
[206]	train-mlogloss:0.64904	eval-mlogloss:0.63074
[207]	train-mlogloss:0.64902	eval-mlogloss:0.63077
[208]	train-mlogloss:0.64830	eval-mlogloss:0.62999
[209]	train-mlogloss:0.64834	eval-mlogloss:0.62997
[210]	train-mlogloss:0.64834	eval-mlogloss:0.62999
[211]	train-mlogloss:0.64798	eval-mlogloss:0.62960
[212]	train-mlogloss:0.64658	eval-mlogloss:0.62806
[213]	train-mlogloss:0.64602	eval-mlogloss:0.62699
[214]	train-mlogloss:0.64584	eval-mlogloss:0.62674
[215]	train-mlogloss:0.64569	eval-mlogloss:0.62661
[216]	train-mlogloss:0.64569	eval-mlogloss:0.62659
[217]	train-mlogloss:0.64563	eval-mlogloss:0.62666
[218]	train-mlogloss:0.64517	eval-mlogloss:0.62608
[219]	train-mlogloss:0.64286	eval-mlogloss:0.62399
[220]	train-mlogloss:0.64286	eval-mlogloss:0.62398
[221]	train-mlogloss:0.64129	eval-mlogloss:0.62256
[222]	train-mlogloss:0.64130	eval-mlogloss:0.62257
[223]	train-mlogloss:0.64128	eval-mlogloss:0.62257
[224]	train-mlogloss:0.64119	eval-mlogloss:0.62255
[225]	train-mlogloss:0.63920	eval-mlogloss:0.62037
[226]	train-mlogloss:0.63722	eval-mlogloss:0.61778
[227]	train-mlogloss:0.63590	eval-mlogloss:0.61629
[228]	train-mlogloss:0.63591	eval-mlogloss:0.61624
[229]	train-mlogloss:0.63591	eval-mlogloss:0.61634
[230]	train-mlogloss:0.63541	eval-mlogloss:0.61540
[231]	train-mlogloss:0.63543	eval-mlogloss:0.61546
[232]	train-mlogloss:0.63542	eval-mlogloss:0.61548
[233]	train-mlogloss:0.63543	eval-mlogloss:0.61544
[234]	train-mlogloss:0.63543	eval-mlogloss:0.61549
[235]	train-mlogloss:0.63541	eval-mlogloss:0.61556
[236]	train-mlogloss:0.63310	eval-mlogloss:0.61323
[237]	train-mlogloss:0.63310	eval-mlogloss:0.61323
[238]	train-mlogloss:0.63302	eval-mlogloss:0.61313
[239]	train-mlogloss:0.63283	eval-mlogloss:0.61293
[240]	train-mlogloss:0.63084	eval-mlogloss:0.61017
[241]	train-mlogloss:0.63020	eval-mlogloss:0.60941
[242]	train-mlogloss:0.63020	eval-mlogloss:0.60950
[243]	train-mlogloss:0.62857	eval-mlogloss:0.60763
[244]	train-mlogloss:0.62857	eval-mlogloss:0.60764
[245]	train-mlogloss:0.62835	eval-mlogloss:0.60749
[246]	train-mlogloss:0.62836	eval-mlogloss:0.60737
[247]	train-mlogloss:0.62724	eval-mlogloss:0.60617
[248]	train-mlogloss:0.62724	eval-mlogloss:0.60621
[249]	train-mlogloss:0.62725	eval-mlogloss:0.60613
[250]	train-mlogloss:0.62722	eval-mlogloss:0.60608
[251]	train-mlogloss:0.62725	eval-mlogloss:0.60605
[252]	train-mlogloss:0.62493	eval-mlogloss:0.60381
[253]	train-mlogloss:0.62472	eval-mlogloss:0.60363
[254]	train-mlogloss:0.62354	eval-mlogloss:0.60233
[255]	train-mlogloss:0.62337	eval-mlogloss:0.60207
[256]	train-mlogloss:0.62129	eval-mlogloss:0.59989
[257]	train-mlogloss:0.62128	eval-mlogloss:0.59982
[258]	train-mlogloss:0.62123	eval-mlogloss:0.59970
[259]	train-mlogloss:0.61924	eval-mlogloss:0.59735
[260]	train-mlogloss:0.61908	eval-mlogloss:0.59715
[261]	train-mlogloss:0.61750	eval-mlogloss:0.59555
[262]	train-mlogloss:0.61705	eval-mlogloss:0.59467
[263]	train-mlogloss:0.61703	eval-mlogloss:0.59468
[264]	train-mlogloss:0.61699	eval-mlogloss:0.59469
[265]	train-mlogloss:0.61697	eval-mlogloss:0.59469
[266]	train-mlogloss:0.61658	eval-mlogloss:0.59432
[267]	train-mlogloss:0.61653	eval-mlogloss:0.59432
[268]	train-mlogloss:0.61614	eval-mlogloss:0.59405
[269]	train-mlogloss:0.61588	eval-mlogloss:0.59358
[270]	train-mlogloss:0.61549	eval-mlogloss:0.59276
[271]	train-mlogloss:0.61547	eval-mlogloss:0.59278
[272]	train-mlogloss:0.61545	eval-mlogloss:0.59275
[273]	train-mlogloss:0.61545	eval-mlogloss:0.59282
[274]	train-mlogloss:0.61545	eval-mlogloss:0.59288
[275]	train-mlogloss:0.61546	eval-mlogloss:0.59286
[276]	train-mlogloss:0.61546	eval-mlogloss:0.59288
[277]	train-mlogloss:0.61516	eval-mlogloss:0.59261
[278]	train-mlogloss:0.61393	eval-mlogloss:0.59141
[279]	train-mlogloss:0.61394	eval-mlogloss:0.59142
[280]	train-mlogloss:0.61396	eval-mlogloss:0.59133
[281]	train-mlogloss:0.61381	eval-mlogloss:0.59122
[282]	train-mlogloss:0.61335	eval-mlogloss:0.59089
[283]	train-mlogloss:0.61333	eval-mlogloss:0.59087
[284]	train-mlogloss:0.61332	eval-mlogloss:0.59088
[285]	train-mlogloss:0.61330	eval-mlogloss:0.59095
[286]	train-mlogloss:0.61326	eval-mlogloss:0.59102
[287]	train-mlogloss:0.61158	eval-mlogloss:0.58899
[288]	train-mlogloss:0.61157	eval-mlogloss:0.58898
[289]	train-mlogloss:0.61128	eval-mlogloss:0.58851
[290]	train-mlogloss:0.61122	eval-mlogloss:0.58845
[291]	train-mlogloss:0.61021	eval-mlogloss:0.58739
[292]	train-mlogloss:0.61020	eval-mlogloss:0.58745
[293]	train-mlogloss:0.60972	eval-mlogloss:0.58660
[294]	train-mlogloss:0.60958	eval-mlogloss:0.58647
[295]	train-mlogloss:0.60797	eval-mlogloss:0.58474
[296]	train-mlogloss:0.60797	eval-mlogloss:0.58476
[297]	train-mlogloss:0.60796	eval-mlogloss:0.58479
[298]	train-mlogloss:0.60774	eval-mlogloss:0.58472
[299]	train-mlogloss:0.60775	eval-mlogloss:0.58468

[I 2025-09-14 02:40:20,370] Trial 21 finished with value: 0.9333333333333333 and parameters: {'lambda': 0.3217820102382774, 'alpha': 0.014793475666229574, 'eta': 0.011641628244913965, 'gamma': 9.701052897531122e-06, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.4020296766466314, 'colsample_bytree': 0.9897219491159328}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08788	eval-mlogloss:1.08737
[1]	train-mlogloss:1.07865	eval-mlogloss:1.07611
[2]	train-mlogloss:1.06866	eval-mlogloss:1.06614
[3]	train-mlogloss:1.05855	eval-mlogloss:1.05643
[4]	train-mlogloss:1.04673	eval-mlogloss:1.04421

[I 2025-09-14 02:40:21,326] Trial 22 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05573	eval-mlogloss:1.05369
[1]	train-mlogloss:1.01996	eval-mlogloss:1.01648
[2]	train-mlogloss:0.98276	eval-mlogloss:0.97984
[3]	train-mlogloss:0.93214	eval-mlogloss:0.92932
[4]	train-mlogloss:0.89343	eval-mlogloss:0.88921

[I 2025-09-14 02:40:21,432] Trial 23 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05646	eval-mlogloss:1.05081
[1]	train-mlogloss:0.99331	eval-mlogloss:0.98489
[2]	train-mlogloss:0.93490	eval-mlogloss:0.92380
[3]	train-mlogloss:0.87968	eval-mlogloss:0.86554

[I 2025-09-14 02:40:21,496] Trial 24 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.94461	eval-mlogloss:0.93675

[I 2025-09-14 02:40:21,540] Trial 25 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.94375	eval-mlogloss:0.93394
[1]	train-mlogloss:0.84385	eval-mlogloss:0.82176

[I 2025-09-14 02:40:21,615] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99232	eval-mlogloss:1.00058

[I 2025-09-14 02:40:21,647] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.91944	eval-mlogloss:0.89022
[1]	train-mlogloss:0.69768	eval-mlogloss:0.66151

[I 2025-09-14 02:40:21,695] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85529	eval-mlogloss:0.85428

[I 2025-09-14 02:40:21,729] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02288	eval-mlogloss:1.02201
[1]	train-mlogloss:0.93245	eval-mlogloss:0.92691
[2]	train-mlogloss:0.85268	eval-mlogloss:0.84250
[3]	train-mlogloss:0.78160	eval-mlogloss:0.76900
[4]	train-mlogloss:0.71906	eval-mlogloss:0.70459

[I 2025-09-14 02:40:22,129] Trial 30 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.09205	eval-mlogloss:1.09276
[1]	train-mlogloss:1.08580	eval-mlogloss:1.08649
[2]	train-mlogloss:1.07767	eval-mlogloss:1.07804
[3]	train-mlogloss:1.07363	eval-mlogloss:1.07363
[4]	train-mlogloss:1.06506	eval-mlogloss:1.06525
[5]	train-mlogloss:1.05679	eval-mlogloss:1.05703
[6]	train-mlogloss:1.04933	eval-mlogloss:1.04973
[7]	train-mlogloss:1.04176	eval-mlogloss:1.04180
[8]	train-mlogloss:1.04174	eval-mlogloss:1.04190
[9]	train-mlogloss:1.03480	eval-mlogloss:1.03481
[10]	train-mlogloss:1.03037	eval-mlogloss:1.03072
[11]	train-mlogloss:1.02146	eval-mlogloss:1.02091
[12]	train-mlogloss:1.01198	eval-mlogloss:1.01163
[13]	train-mlogloss:1.00834	eval-mlogloss:1.00797
[14]	train-mlogloss:1.00419	eval-mlogloss:1.00364
[15]	train-mlogloss:0.99577	eval-mlogloss:0.99506

[I 2025-09-14 02:40:22,728] Trial 31 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.07983	eval-mlogloss:1.07958
[1]	train-mlogloss:1.06604	eval-mlogloss:1.06514
[2]	train-mlogloss:1.04850	eval-mlogloss:1.04754
[3]	train-mlogloss:1.03262	eval-mlogloss:1.03157
[4]	train-mlogloss:1.01552	eval-mlogloss:1.01555

[I 2025-09-14 02:40:22,775] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07400	eval-mlogloss:1.07264
[1]	train-mlogloss:1.05254	eval-mlogloss:1.04712
[2]	train-mlogloss:1.02877	eval-mlogloss:1.02308
[3]	train-mlogloss:1.00488	eval-mlogloss:1.00004
[4]	train-mlogloss:0.97828	eval-mlogloss:0.97257

[I 2025-09-14 02:40:22,835] Trial 33 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03222	eval-mlogloss:1.02910

[I 2025-09-14 02:40:22,951] Trial 34 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06575	eval-mlogloss:1.06286
[1]	train-mlogloss:1.03826	eval-mlogloss:1.03140
[2]	train-mlogloss:1.00385	eval-mlogloss:0.99595
[3]	train-mlogloss:0.96719	eval-mlogloss:0.95729

[I 2025-09-14 02:40:23,114] Trial 35 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.00399	eval-mlogloss:0.99805

[I 2025-09-14 02:40:23,169] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89357	eval-mlogloss:0.87620
[1]	train-mlogloss:0.74349	eval-mlogloss:0.71403

[I 2025-09-14 02:40:23,233] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97298	eval-mlogloss:0.98244

[I 2025-09-14 02:40:23,282] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.98946	eval-mlogloss:0.99336
[1]	train-mlogloss:0.86695	eval-mlogloss:0.86023

[I 2025-09-14 02:40:23,618] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.80519	eval-mlogloss:0.78301

[I 2025-09-14 02:40:24,140] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03430	eval-mlogloss:1.03054
[1]	train-mlogloss:0.97558	eval-mlogloss:0.97030

[I 2025-09-14 02:40:25,003] Trial 41 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06389	eval-mlogloss:1.06130
[1]	train-mlogloss:1.03142	eval-mlogloss:1.02795
[2]	train-mlogloss:0.99776	eval-mlogloss:0.99334
[3]	train-mlogloss:0.96586	eval-mlogloss:0.95904

[I 2025-09-14 02:40:25,125] Trial 42 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.97785	eval-mlogloss:0.97666

[I 2025-09-14 02:40:25,346] Trial 43 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04423	eval-mlogloss:1.04467
[1]	train-mlogloss:0.97664	eval-mlogloss:0.97412

[I 2025-09-14 02:40:25,523] Trial 44 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01364	eval-mlogloss:1.00846
[1]	train-mlogloss:0.94196	eval-mlogloss:0.93506

[I 2025-09-14 02:40:25,669] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08443	eval-mlogloss:1.08357
[1]	train-mlogloss:1.07336	eval-mlogloss:1.07121
[2]	train-mlogloss:1.05954	eval-mlogloss:1.05644
[3]	train-mlogloss:1.04490	eval-mlogloss:1.04122
[4]	train-mlogloss:1.03198	eval-mlogloss:1.02783

[I 2025-09-14 02:40:26,159] Trial 46 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.96440	eval-mlogloss:0.95293

[I 2025-09-14 02:40:26,259] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92616	eval-mlogloss:0.91464

[I 2025-09-14 02:40:26,338] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06906	eval-mlogloss:1.06721
[1]	train-mlogloss:1.04050	eval-mlogloss:1.03469
[2]	train-mlogloss:1.01340	eval-mlogloss:1.00800
[3]	train-mlogloss:0.98247	eval-mlogloss:0.97495
[4]	train-mlogloss:0.95393	eval-mlogloss:0.94552

[I 2025-09-14 02:40:26,491] Trial 49 pruned. Trial was pruned at iteration 4.

Best trial: {'lambda': 1.2250904678513507e-07, 'alpha': 3.6114636955552215e-07, 'eta': 0.23828434454277586, 'gamma': 0.023318103669313976, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.4588392809168451, 'colsample_bytree': 0.5177577376554756}
Best accuracy: 1.0